# Generated by Django 6.0.3 on 2026-03-23 22:28

import wallet.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=wallet.utility.generate_reference_id, max_length=100, unique=True),
        ),
    ]
